[package]
name = "cardamon"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
uuid = { version = "1.12.1", features = ["v5"] }
